### ISSUE TITLE
Initial code commit.

### ISSUE THREAD

**Issue by Veski0** [marleysudbury/PapaKirill#11]
At some point we're going to need to commit some code to this repository so that everyone can branch it. This should be the first thing we think about when we meet next on Thursday. It's pretty much as simple as one of us pushing a completing, working and extensible game2_templates to the repository but it might be nice to compare code in person first before we decide whose code to initially push.

**Comment by marleysudbury** [comment]
Definitely. The code will probably need to be tidied up in any case, to remove the template instructions.

**Comment by marleysudbury** [comment]
Code has been commited 👍
