### ISSUE TITLE
Cut scene text scroller

### ISSUE THREAD

**Issue by Veski0** [marleysudbury/PapaKirill#18]
Scrolls text with each enter press.

**Comment by marleysudbury** [comment]
Start in a cab, explaining his story to the driver.
Gets to his pizzeria, blood everywhere.
Calls up the police station, but me through to Bob. (Kirrill is an ex detective)
Bob sends a police team.
Kirill is seriously dissappointed because there is no evidence.
Vows to avenge his uncle.

**Comment by marleysudbury** [comment]
For the purposes of demonstration, it would be really useful to be able to skip the slow scroll. Maybe pressing ENTER could skip to the next line, increase speed or skip to the end of the whole text?
